# Generated by Django 4.1.7 on 2023-07-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('h1', models.CharField(default='related to which area', max_length=100)),
                ('h2', models.CharField(default='title of blog post', max_length=100)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('p2', models.CharField(default='description', max_length=1000)),
                ('thumbnail', models.ImageField(default='upload image', upload_to='blog/images')),
            ],
        ),
    ]
