# Generated by Django 4.1.7 on 2023-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=' not available', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.CharField(default='not available', max_length=80),
        ),
    ]
