# Generated by Django 4.1.7 on 2023-03-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_price_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subCategory',
            new_name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='not found', upload_to='shop/images'),
        ),
    ]
