# Generated by Django 4.1.7 on 2023-06-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default=' not available', max_length=70)),
                ('phone', models.IntegerField(default='not available')),
                ('desc', models.CharField(max_length=600)),
                ('date', models.DateField()),
            ],
        ),
    ]
