# Generated by Django 4.1.7 on 2023-06-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_contact_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='yourItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
