# Generated by Django 4.1.7 on 2023-06-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_yourcart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='nil', max_length=50)),
                ('email', models.CharField(default=' not available', max_length=70)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=150)),
                ('state', models.CharField(default='nil', max_length=50)),
                ('city', models.CharField(default=' not available', max_length=70)),
                ('zip', models.CharField(default=' not available', max_length=70)),
            ],
        ),
    ]
