# Generated by Django 4.1.7 on 2023-06-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
