# Generated by Django 4.1.7 on 2023-06-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_item_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default=' not available', max_length=700),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default=' not available', max_length=700),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='nil', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip',
            field=models.CharField(default=' not available', max_length=700),
        ),
    ]
