# Generated by Django 4.1.7 on 2023-06-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('email', models.CharField(max_length=111)),
                ('update_desc', models.CharField(max_length=5000)),
            ],
        ),
    ]
