# Generated by Django 4.1.7 on 2023-06-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='item_json',
            field=models.CharField(default='not given', max_length=1000),
        ),
    ]
