# Generated by Django 4.1.7 on 2023-06-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orderupdate_item_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
