# Generated by Django 4.1.7 on 2023-06-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orderupdate_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timeStamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
