# Generated by Django 4.1.7 on 2023-06-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='item_json',
        ),
    ]
