# Generated by Django 4.1.7 on 2023-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
